### ISSUE TITLE
Bump to jb 0.9.0 (or later)

### ISSUE THREAD

**Issue by joergbrech** [joergbrech/Modellbildung-und-Simulation#100]
...once it has been released. Then, we can remove the redundant jb book requirement from here:

https://github.com/joergbrech/Modellbildung-und-Simulation/blob/7d6d2058b4faca4a00e4a428e9a32733fcac85ff/requirements.txt#L2

See this [PR comment](https://github.com/joergbrech/Modellbildung-und-Simulation/pull/98#issuecomment-744243015) on #98 .

**Comment by sandro-elsweijer** [comment]
I don't know if this solves the Problem. The sphinx-bibtex incompatibility is not version specific and also happens on jb 0.7.2

**Comment by joergbrech** [comment]
The incompatibility is introduced in sphinx-bibtex 2.0 and the dependency of jb book to sphinxcontrib-bibtex==1.0.0 has been pinned in the `setup.py` script of jb book yesterday: https://github.com/executablebooks/jupyter-book/commit/e143e44f0b37225cd50258fb5d5d8ae2ece968b9 

So if we install jb book from the current master branch, or wait for a new release off of the current master branch, the dependency will be pinned by jb book and we don't have to take care of it here. So removing the line from the `requirements.txt` is fine.

This is the cleaner solution, since on the jb side they are likely to decide to adapt their code to be compartible with sphinxcontrib-bibtex 2.x sometime in the future, which will cause our builds to fail if we require sphinxcontrib-bibtex==1.0.0.
