### ISSUE TITLE
Add exercise for stability of Euler integrator

### ISSUE THREAD

**Issue by joergbrech** [joergbrech/Modellbildung-und-Simulation#102]
Let the user play around with different ODE solvers and time steps so that he/she can develop a feeling for the influence of the parameters.

**Comment by PhiSpel** [comment]
look into Prothero-Robinson equation

**Comment by PhiSpel** [comment]
Drafted a small 
[Exercise for stability of Euler integrator.docx](https://github.com/joergbrech/Modellbildung-und-Simulation/files/6211869/Exercise.for.stability.of.Euler.integrator.docx)

Going into depth with the Prothero-Robinson-Example would add a lot of content - this may be unwanted.

For the Dahlquist-Equation I modified the code from the lectures in [Dahlquist.m.txt](https://github.com/joergbrech/Modellbildung-und-Simulation/files/6211874/Dahlquist.m.txt). This code could be used by the students to identify significant values for lambda and h.

Looking forward to hearing your opinions on April 14th.
