### ISSUE TITLE
Embed Patrick's Youtube Videos

### ISSUE THREAD

**Issue by joergbrech** [joergbrech/Modellbildung-und-Simulation#103]
We should think about which videos we can embed in which exercises in the book and add links.

_Edit by Philipp:_

Start with MATLAB introduction exercise

**Comment by PhiSpel** [comment]
There are four lists of "Übungsaufgaben":

1. MATLAB für Ingenieure
- available @ https://youtube.com/playlist?list=PLmClq2ZJ_PtuIEIJOpXwu0xQPwlzw3whv
	- WS20/21 exercises 1 to 7 (8 to 10 tba.)
	- WS19/20 exercises 5 to 6
	- WS18/19 exercises 7 to 10
- partial content-overlap with ModSim

2. Modellbildung und Simulation 1 SoSe 2018
- available @ modsim-buchprojekt/material/Quellen_Gerd/
	- Übung 3 reappears in MATLAB für Ingenieure Übung 5
- not used anywhere else

3. Modellbildung und Simulation 1 Book / Script
- available @ modsim-buchprojekt/script/uebungen/ue01_schwingungen.tex AND modsim-buchprojekt/book/uebungen/ue01_schwingungen.tex
	- --> move to a common folder?
- 7 exercises

4. Modellbildung und Simulation 1 + 2 Übung-Veranstaltung
- in Patricks List
- ModSim 2 available @ https://www.youtube.com/playlist?app=desktop&list=PLmClq2ZJ_PttYuHeru_c1HwNk670ekWBd
- exercises from different sources (script and separate sheets)
- 10 + 9 exercises

Takeaway:
- overlap between MATLAB fIng and ModSim
- exercises and videos should be sorted by domain to determine, which can be best used (I'm on it)

**Comment by PhiSpel** [comment]
Developed a [List of ModSim Exercises.xlsx](https://github.com/joergbrech/Modellbildung-und-Simulation/files/6211895/List.of.ModSim.Exercises.xlsx)

I can sort out in more detail, which content can be used for which topic after Easter.

**Comment by PhiSpel** [comment]
#197 suffices
