### ISSUE TITLE
Add exercise that models slackline as a PDE

### ISSUE THREAD

**Issue by joergbrech** [joergbrech/Modellbildung-und-Simulation#123]
This can be an extension of the slackline as linear system and #56

**Comment by PhiSpel** [comment]
first include highline in eigen-value, see #129

**Comment by PhiSpel** [comment]
Should finite differences be introduced elsewhere?

**Comment by PhiSpel** [comment]
After including finite differences for space-derivatives in the PDE, the resulting ODE is equivalent to the ODE in the first two highline exercises. Maybe we include the PDE exercise as additional information to make the transition from PDE to ODE clearer?
