### ISSUE TITLE
Traffic jam problem as motivating chapter

### ISSUE THREAD

**Issue by sandro-elsweijer** [joergbrech/Modellbildung-und-Simulation#130]
Edit by Philipp:

- [x] Should we include the Traffic-PDE in the PDE chapter? Like this, we can have two examples throughout the book, Highline and Traffic

**Comment by PhiSpel** [comment]
- [ ] how did the physical model become the best model? For me, it only results in such high number of cars and speed-limits if i set accelleration to >30 m/s^2
- [ ] include a more complex simulation
