### ISSUE TITLE
Korrekturlesen der bis jetzt vorhanden Seiten

### ISSUE THREAD

**Issue by joergbrech** [joergbrech/Modellbildung-und-Simulation#18]
Korrekturlesen sollte eigentlich kein separates Issue sein, aber da einige der Seiten unter Zeitdruck entstanden sind, lohnt es sich einmal alle bis jetzt vorhandenen Seiten auf Rechtschreibung, Grammatik und Formulierung durchzuschauen...

**Comment by MartinKliemank** [comment]
Ich habe mal einen branch dafür angefangen, bisher habe ich vom Kapitel 00_Einführung alles außer Matlab_02 und Matlab_03 geschafft...
Dabei sind mir einige Fragen gekommen:
schreiben wir Zahlen außerhalb vom Code mit Komma oder mit Punkt? 12,5 € oder 12.5 € ?
Differential oder Differenzial? (Duden favorisiert die Schreibweise mit z, aber die andere scheint mir die üblichere zu sein?)

**Comment by joergbrech** [comment]
Danke, @reitd000 wollte glaube ich auch was lesen, vllt sprecht ihr euch ab, so dass ihr nicht doppelte Arbeit macht?

 - Ich habe mir angewöhnt (zumindest im Ingenieursbereich) kein Dezimalkomma zu verwenden, nur noch den Dezimalpunkt. Man programmiert mit Dezimalpunkt und die Lingua Franca ist Englisch. Wir können das aber gerne diskutieren?
 - Ich finde, dass Differenzial mit z komisch aussieht, das kann aber auch nur an mir persönlich liegen. Auch hier lass ich mich gerne vom Gegenteil überzeugen. Am Ende ist es mir eigentlich egal, hauptsache es ist einheitlich.

**Comment by MartinKliemank** [comment]
Ich poste Herrn Reiths Antwort-Email der Vollständigkeit halber hier auch noch mal:

> Hi folks,
>  
> ich schließe mich Jan voll und ganz an:  Punkte und bitte „t“, nicht „z“.  :-)
>  
> Ansonsten muss ich leider sagen, dass ich und in Ungarn bei der Formula Student auch mein Rechner den Temperaturen zum Opfer gefallen bin; das Ladekabel mitzunehmen wäre natürlich auch sinnvoll gewesen…. Bin von daher so gar nicht zufrieden mit mir, aber nun wird es (Ende) August mit Korrekturen meinerseits.
>  
> … dafür habe ich heute mal einen Forumseintrag verfasst, der mir dringend nötig erschien. Ich hoffe, ich bin nicht übers Ziel hinausgeschossen.
>  
> LG, schönen Sommer & bis bald,
>  
> DR
>

**Comment by MartinKliemank** [comment]
Ansonsten bin ich ganz bei euch, was Punkte (die Kommas verleiten ja doch schnell zu Programmierfehlern, wenn man daran nicht gewöhnt ist und die Wert übernimmt) und t angeht. Ich finde auch, dass es mit z komisch aussieht. (Ich ändere das dann in den Seiten, die ich schon gelesen hatte auch nochmal entsprechend)

Vll sollten wir solche Konventionen auch noch im Contributing als Übersicht festhalten?

**Comment by joergbrech** [comment]
Hi, 

wegen mir können wir gerne solche Konventionen irgendwo (zum Beispiel im Wiki) dokumentieren und diese Stellen im Contributing.md verlinken?

**Comment by joergbrech** [comment]
closed with #29
