### ISSUE TITLE
MATLAB Grundlagenkurs Übungsblätter

### ISSUE THREAD

**Issue by PhiSpel** [joergbrech/Modellbildung-und-Simulation#181]
- [x] how to integrate the tasks from PDF? (in which format? as file or included in the JupyterNB?)
- [x] --> add separate pages including videos
- [x] should this be a separate chapter?
- [ ] #274
- [x] dicuss with the team: How should the MATLAB course relate to the rest? (I think, it should be included as it is, and referred to as it is. Otherwise, it would need too much reworking and we would need examples from other domains - which are not helping in other exercises - to properly avoid overlap.)

See LEA Course for Data

**Comment by PhiSpel** [comment]
For the exercises in this book, quite some basics in MATLAB are required. These can be aquired separately **or** using the exercises. I would suggest moving all MATLAB-Syntax (with the exception of
1) the MoXUnit explanation in Verwendung dieses Buches and
2) Erste Schritte in Matlab > "Best Practices"
to a separate chapter in the end, something like "Grundlagen: MATLAB"

Like this, the "Modellbildung und Simulation" book is still just that. For the MATLAB-specific syntax, the separate chapter can be consulted

**Comment by joergbrech** [comment]
Good suggestion. Currently, the book is still very Matlab/Octave specific, but since we want to change that in the long run, this is a good start. In the future we could have similar chapters for python and julia.
