### ISSUE TITLE
convection-diffusion: Compare Euler to CN in exercise 2

### ISSUE THREAD

**Issue by joergbrech** [joergbrech/Modellbildung-und-Simulation#191]
Going over the exercise 2 again, I realized, that we should probably also provide some more explicit instructions for numerical experminets regarding the comparison of the explicit Euler and the Crank-Nicolson regimes. In you rplots its hard to see a difference, I assume because the step size is chosen small enough. But this is definitely something for a new issue. Let's merge!

_Originally posted by @joergbrech in https://github.com/joergbrech/Modellbildung-und-Simulation/issues/188#issuecomment-930223864_

**Comment by PhiSpel** [comment]
will be solved in #195
