### ISSUE TITLE
Integration Aufgabe

### ISSUE THREAD

**Issue by joergbrech** [joergbrech/Modellbildung-und-Simulation#23]
Edit by Philipp:

- [x] MoxUnit did not work on my Octave, only offline after installing it manually using the instructions on https://github.com/MOxUnit/MOxUnit
- [x] is it necessary to check the stepsize `df`?

**Comment by MartinKliemank** [comment]
z.B: Übung7 Aufgabe 3 Modsim 1 2018

**Comment by PhiSpel** [comment]
- [x] still need to fix numInt.m example file for f=1/x (continuous loop)
- [ ] MoxUnit did not work on my Octave, only offline after installing it manually using the instructions on https://github.com/MOxUnit/MOxUnit
- [ ] is it necessary to check the stepsize `df`?
