### ISSUE TITLE
Contributing.md toc workflow

### ISSUE THREAD

**Issue by PhiSpel** [joergbrech/Modellbildung-und-Simulation#232]
Currently it says `jupyter-book toc from-project -e .ipynb -e .md -f jb-book content/ > content/_toc.yml`

Shouldn't `jupyter-book toc content` be enough?

**Comment by joergbrech** [comment]
Good question. Have you tried? @sandro-elsweijer, do you remember why you had to change the command in commit https://github.com/joergbrech/Modellbildung-und-Simulation/commit/cf3a8e54ea16829aac43dcc52280813ce4579c43?

**Comment by PhiSpel** [comment]
> Have you tried?

I always use that command :)

**Comment by joergbrech** [comment]
If the shorter command works, I vote for changing it *both in the circle ci setup and the Contributing markdown file*. But let's wait for feedback from @sandro-elsweijer, because he introduced this change.

**Comment by PhiSpel** [comment]
For @VictorLued it works only with Sandros changes. So I guess I am using an older version :)
