### ISSUE TITLE
Add Victor and Flo as contributors

### ISSUE THREAD

**Issue by PhiSpel** [joergbrech/Modellbildung-und-Simulation#234]
The team is growing! :)

Victor is @VictorLued

**Comment by joergbrech** [comment]
👋 We should remember to add Victor and Flo also to the author list in https://github.com/joergbrech/Modellbildung-und-Simulation/blob/master/.zenodo.json, once they have made their first contribution on `master` 😃

**Comment by PhiSpel** [comment]
Flo is @Florian314

**Comment by PhiSpel** [comment]
> Flo is @Florian314

@joergbrech did you add Flo?

**Comment by PhiSpel** [comment]
They have access now :)
