### ISSUE TITLE
Remove example solutions

### ISSUE THREAD

**Issue by PhiSpel** [joergbrech/Modellbildung-und-Simulation#264]
As this repo is public, example solutions should be stored [here](https://github.com/hbrs-cse/modsim-Musterloesungen)

- [x] @PhiSpel delete example solutions
- [x] @joergbrech can we hide those deleted files / permanently delete them?

**Comment by joergbrech** [comment]
> @joergbrech can we hide those deleted files / permanently delete them? 

Tricky, but possible. It depends on when and how the solutions were added. I wasn't aware that we published any solutions, here. 🤔 Could you give an example?

**Comment by PhiSpel** [comment]
> > @joergbrech can we hide those deleted files / permanently delete them?
> 
> Tricky, but possible. It depends on when and how the solutions were added. I wasn't aware that we published any solutions, here. 🤔 Could you give an example?

I had added [Modellbildung-und-Simulation](https://github.com/joergbrech/Modellbildung-und-Simulation)/[content](https://github.com/joergbrech/Modellbildung-und-Simulation/tree/master/content)/[02_gleitkommaarithmetik](https://github.com/joergbrech/Modellbildung-und-Simulation/tree/master/content/02_gleitkommaarithmetik)/Taylor4sin.m, but this should not be a big deal. I double-checked the other folders, there is nothing there. So if Taylor is not something for the near future (plus its not the most sophisticated solution), it could also be fine

**Comment by PhiSpel** [comment]
Should be fine

**Comment by joergbrech** [comment]
I agree, rewriting master because of this would be kind of overkill...
