### ISSUE TITLE
Issue with TOC

### ISSUE THREAD

**Issue by joergbrech** [joergbrech/Modellbildung-und-Simulation#275]
- Currently, Game Of Life is in https://joergbrech.github.io/Modellbildung-und-Simulation/00_einleitung/00_einleitung.html#, while it should be in https://joergbrech.github.io/Modellbildung-und-Simulation/01_uebungen/00_uebungsaufgaben.html
 - https://joergbrech.github.io/Modellbildung-und-Simulation/01_uebungen/00_uebungsaufgaben.html I am not entirely happy with the title, because the whole online book is Übungsaufgaben. Could we maybe rename this to "Einleitende Übungsaufgabe" or similar? We should also mention in the introductory text, that this chapter contains all exercises that can be done with minimal to no prior knowledge on Modellbildung und Simulation.

**Comment by PhiSpel** [comment]
I included the movement of Game of Life in #206 and will also include the name change
