### ISSUE TITLE
Reorganize images in content folder

### ISSUE THREAD

**Issue by joergbrech** [joergbrech/Modellbildung-und-Simulation#31]

**Comment by prosauer** [comment]
@joergbrech would you prefer to restructure the images inside the current folder, or  to add one image subfolder inside each chapter folder? 
Also: As I will move each image and change the file-path in each chapter, is a uniform naming system useful? Or is this needless, as we will have subfolders with descriptive names?

**Comment by joergbrech** [comment]
I think a subfolder in each chapter makes more sense. A uniform naming system is high maintainance, the only requirement is that all subfolders containing images should be named `images` because of this line:

https://github.com/joergbrech/Modellbildung-und-Simulation/blob/b45e1c4d72778d164a18f55db343ae2026dc123f/.circleci/config.yml#L34

Explanation: With the new backend, images using pure html, i.e. `<img src=...>` are not supported anymore. As a consequence, they only get rendered correctly in the generated site, if we manually copy the images to the `_build/html` directory. That's why I added the above line to the circleci config.

PS: I am actually a bit annoyed by the naming system we use so far, naming all notebooks `exercises_XX_smthg`. This seems a bit overengineered and I don't see the point (I know, I started it, my bad 😝 ).

**Comment by joergbrech** [comment]
Oh, if you don't mind: If you have to go through all notebooks anyway, do you think you could fix #74 in the same go? 😃

**Comment by prosauer** [comment]
> 
> 
> Oh, if you don't mind: If you have to go through all notebooks anyway, do you think you could fix #74 in the same go? 😃

sure!



> 
> 
> I think a subfolder in each chapter makes more sense. A uniform naming system is high maintainance, the only requirement is that all subfolders containing images should be named `images` because of this line:
> 
> https://github.com/joergbrech/Modellbildung-und-Simulation/blob/b45e1c4d72778d164a18f55db343ae2026dc123f/.circleci/config.yml#L34
> 
> Explanation: With the new backend, images using pure html, i.e. `<img src=...>` are not supported anymore. As a consequence, they only get rendered correctly in the generated site, if we manually copy the images to the `_build/html` directory. That's why I added the above line to the circleci config.
> 
> PS: I am actually a bit annoyed by the naming system we use so far, naming all notebooks `exercises_XX_smthg`. This seems a bit overengineered and I don't see the point (I know, I started it, my bad 😝 ).

Okay! Regarding naming of notebooks: Renaming would require renaming of the notebooks+renaming in toc, do I forget something more? I'll create an issue and could fix it in the same go! 😉

**Comment by joergbrech** [comment]
> Regarding naming of notebooks: Renaming would require renaming of the notebooks+renaming in toc, do I forget something more?

There are also hard coded cross references in some of the notebooks. Sphinx will throw a warning if the targets cannot be found during the call to `jupyter-book build content` so they should be easy to spot. A better way of implementing these hard-coded cross references would be to use this: https://jupyterbook.org/content/citations.html#cross-references-and-labels

But fixing this is not superimportant, this issue is already getting bigger and bigger as it is :wink:
