### ISSUE TITLE
Modellbildung und Simulation Main Page dead!

### ISSUE THREAD

**Issue by joergbrech** [joergbrech/Modellbildung-und-Simulation#353]
#351 killed the main page. Both Philipp and me forgot to check the demo site before merging because it was such a small change.

**Comment by PhiSpel** [comment]
The artifacts in #351 were fine, see [CircleCI](https://app.circleci.com/pipelines/github/joergbrech/Modellbildung-und-Simulation/1302/workflows/8f5246b3-711c-4dae-a4a3-333131417514/jobs/2502/artifacts)
