### ISSUE TITLE
Correct Author Attribution

### ISSUE THREAD

**Issue by joergbrech** [joergbrech/Modellbildung-und-Simulation#41]
There are two ways to do this: 

 - Add an author to each exercise: https://jupyterbook.org/features/titles.html
 - Add (regular) contributors to the list of creators in the zenodo json file.

This depends on #2

**Comment by joergbrech** [comment]
@MartinKliemank @prosauer @reitd000, wie wollen wir das handhaben? Ich sehe drei Möglichkeiten:

1. Ich versuche nach bestem Gewissen überall die Autorenschaft in die jeweiligen Notebooks einzutragen
2. Jeder ist selbst für die Pflege seiner eigenen Autorenschaften verantwortlich. Wenn in einem Notebook kein Autor eingetragen ist, gehe ich davon aus, dass das so gewünscht ist.
3. Wir nutzen das Feature nicht und machen keine explizite Autorenschaft pro Notebook

**Comment by prosauer** [comment]
Meinem Ego reicht es vollkommen, wenn irgendwo steht, dass wir insgesamt Mitautoren sind. Um Fragen zu Kapiteln direkt an den jeweiligen Autor stellen zu können, wäre 2 aber vielleicht sinnvoll? (Wenn dann eine Mail-Addresse verlinkt ist und das gewünscht ist)

**Comment by joergbrech** [comment]
Anscheinend ist das feature beim neuen backend verloren gegangen.
