### ISSUE TITLE
Do citations properly

### ISSUE THREAD

**Issue by joergbrech** [joergbrech/Modellbildung-und-Simulation#42]
Beim Bierschaumzerfall und bei der Verkehrssimulation gibt es Quellenangaben, die händisch eingefügt wurden. Wir solltend as jupyter book feature dazu verwenden:

https://jupyterbook.org/features/citations.html

**Comment by sandro-elsweijer** [comment]
Wie man zitiert ist ziemlich straight forward, allerdings weiß ich nicht, was aus den Büchern stammt und was nicht, da nur das Literaturverzeichnis manuell erstellt wurde, nicht aber die Zitationsmarker im Text. Weiß noch jemand was genau in den Kapiteln zitiert wurde?

**Comment by joergbrech** [comment]
Im ersten Fall wird das Verkehrssimulationsmodell (Das Nagel-Schreckenberg-Modell) aus dem Paper verwendet und beim Bierschaumzerfall handelt es sich mehr um weiterführende Literatur. Das Bierschaumzerfallexperiment ist weit verbreitet und in den Quellen wird ein wenig mehr ins Detail gegangen. Insofern ist es in diesen Fällen ok, das ganze Paper als Quelle anzugeben und keine explizite Zitationsmarker im Text zu setzen.

**Comment by sandro-elsweijer** [comment]
Bei Verwendung der angegebenen Befehle `{% cite bibtex_shortname %}` und `{% bibliography --cited %}` werden diese nicht erkannt und so 1 zu 1 auf die Jupyter Seite übernommen.
![image](https://user-images.githubusercontent.com/49643115/79067298-9eea3100-7cbe-11ea-9d28-0d2ab3e301f3.png) 
Ich denke, dass es etwas mit unserer Nutzung von Markdown und dem Disclaimer zu tun hat:
> Note that this only works if you're building your book HTML locally and hosting the HTML files online somewhere. This can still use GitHub pages, but not the auto-generation of a cite from markdown files feature of GitHub pages. This is because GitHub pages doesn't include the jekyll-scholar plugin.

**Comment by joergbrech** [comment]
Das Zitieren funktioniert schon, siehe https://482-168147770-gh.circle-artifacts.com/0/html/04_nichtlineare_gleichungen/exercises_00_bierschaum.html#Literatur

Das Zitat ist im notebook nur noch nicht sichtbar, da es erst später mit jekyll konvertiert wird.
