### ISSUE TITLE
Delete Spline-Interpolation-p34 Branch

### ISSUE THREAD

**Issue by MartinKliemank** [joergbrech/Modellbildung-und-Simulation#45]
Der Spline-Interpolation-P34 Branch ist, laut meinen "Untersuchungen" nur ein Rest, aus dem der neue Branch, den wir gestern gemerged haben, geworden ist. Dementsprechend kann der verbliebene Branch gelöscht werden.
Ich habe leider die Option dafür nicht finden können.

**Comment by joergbrech** [comment]
Done! Wenn man auf "branches" ist hinter jedem branch ein Mülleimer
