### ISSUE TITLE
Adaptives Zeitschrittverfahren

### ISSUE THREAD

**Issue by joergbrech** [joergbrech/Modellbildung-und-Simulation#69]
Aufbauend auf @MartinKliemank's Aufgabe zur numerischen Integration könnte man die Studierende unter Anleitung ein adaptives Zeitschrittverfahren auf Basis von `numInt` im Kapitel zu gewöhnlichen Differentialgleichungen programmieren lassen.

Dafür muss natürlich erstmal #46 gemerged werden.

**Comment by PhiSpel** [comment]
> adaptive Runge-Kutta method (eingebettetes Runge-Kutta Verfahren) of low order

-> part of `07_num_ode/`
