### ISSUE TITLE
Praktikumsaufgaben einpflegen.

### ISSUE THREAD

**Issue by joergbrech** [joergbrech/Modellbildung-und-Simulation#7]
Die Praktikumsaufgaben aus alten Semestern oder der Rücklage sollten hier unter den entsprechenden Kapiteln eingepflegt werden.

Erstmal erstelle ich hier eine Liste, aus der wir dann neue Issues generieren können ;)

**Comment by joergbrech** [comment]
ModSim 2 Praktika: https://gitlab.com/joergbrech/modsim2/-/tree/master/Praktikum

 - Simulink
 - Eigenwerte
 - Fouriertransformation
 - Randwertprobleme
 - PDEs

Werkzeuge: 

 - Git
 - Latex

**Comment by PhiSpel** [comment]
Most exercises are now online or moved to individual issues.

Übungsaufgaben from the lecture will come, see #154

**Comment by PhiSpel** [comment]
Most exercises are now online or moved to individual issues.

Übungsaufgaben from the lecture will come, see #154
