### ISSUE TITLE
Rename Notebooks

### ISSUE THREAD

**Issue by prosauer** [joergbrech/Modellbildung-und-Simulation#83]
- [x] Probably some more complicated stuff, that may need fixing by a higher force
- [x] Discuss new naming system
- [x] Rename all Notebooks
- [x] Update toc.yml

**Comment by prosauer** [comment]
@joergbrech Is it sufficient to delete "exercise_", as this is redundant somehow? Or should we desert numbering, too? I guess descriptive names are useful, so we should keep them?

**Comment by joergbrech** [comment]
I think we have two options, and I am fine with both:

# Option A

notebook names are completely arbitrary, as long as they are descriptive, don't contain any special characters or white spaces. The order of the notebooks is determined by the `_toc.yml`.

# Option B

We use jupyter-book to automatically create the `_toc.yml`. In this case, the naming must adhere to the conventions described here: https://jupyterbook.org/customize/toc.html#automatically-generate-your-toc-yml-file

**Comment by prosauer** [comment]
"automatically" is always great, esp. in this case, as manually updating `_toc.yml` is kind of tedious. 
As I understand, naming "XX_<name>" should be descriptive and meet the reqs and subfolders for chapters already meet them?

**Comment by joergbrech** [comment]
Yes, with some exceptions, especially in the first chapter where there are currently no subsubfolders for the subsubsections. Also, the filenames are used as titles so this would still require some file renaming and moving.

```
jb toc --help
```

```
Usage: jb toc [OPTIONS] PATH

  Generate a _toc.yml file for your content folder (and sub-directories).
  The alpha-numeric name of valid conten files will be used to choose the
  order of pages/sections. If any file is called "index.{extension}", it
  will be chosen as the first file.

Options:
  --filename_split_char TEXT  A character used to split file names for titles
  --skip_text TEXT            If this text is found in any files or folders,
                              they will be skipped.
  --output-folder TEXT        A folder where the TOC will be written. Default
                              is `path`
  --help                      Show this message and exit.
```

**Comment by prosauer** [comment]
So this seems to work fine in general, but I ran into one problem, I can't find a solution for. The title is generated automatically from the filename. e.g. 00_übungen will show as "Übungen" in the navigation sidebar, but 00_differentiation_und_integration will show "Differentiation **U**nd Integration" with a capital U. If there is no way to get around this, it may be easier to keep updating the toc manually.

**Comment by joergbrech** [comment]
Ok, I don't think this is too big an issue. We could also ask in the issue tracker at https://github.com/executablebooks/jupyter-book if the interface can be changed, such that the capitalization of the file names are respected?

**Comment by prosauer** [comment]
Alright, so I will keep the auto-gen of the toc and start to work on the images and fixing the outputs then! 
I asked for help over at https://github.com/executablebooks/jupyter-book, maybe this is possible already and I just don't know how! 👍
