### ISSUE TITLE
Consider building pdf version in CI

### ISSUE THREAD

**Issue by joergbrech** [joergbrech/Modellbildung-und-Simulation#84]
not because we need it, but because that feature exists over at jupyter-book now and I am curious.

**Comment by joergbrech** [comment]
pdflatex and latex will probably not work without painful additional scripting to convert GIFs etc. We can still see if we can get a pretty print version using the pdfhtml builder.

**Comment by PhiSpel** [comment]
@joergbrech do you have new insights to this? It may not make work much easier, as we can already print the CI-html from our browsers

**Comment by joergbrech** [comment]
I also see no real benefit of this...if there are no objections, I say let's close this issue.
