### ISSUE TITLE
automatically generate toc

### ISSUE THREAD

**Issue by prosauer** [joergbrech/Modellbildung-und-Simulation#87]
- [x] bump jb in `requirements.txt` as soon as new jb release is out: https://github.com/executablebooks/jupyter-book/releases
- [x] remove `_toc.yml` from version control
- [x] mention `jb toc` in `CONTRIBUTING.md` 
- [x] add the `jb toc` command to the circleci config

**Comment by joergbrech** [comment]
@prosauer, there has been a new release of jb :slightly_smiling_face:
