### ISSUE TITLE
Enhance the convection-diffusion exercise

### ISSUE THREAD

**Issue by joergbrech** [joergbrech/Modellbildung-und-Simulation#91]
The convection-diffusion exercise would benefit from some additional guidance, such as prepared matlab code, unit tests and some more explanations, images or animations.

This is related to issue #54 and PR #90.

- [x] add graphical output
- [x] code should be parameter-independent
- [x] suggest parameters

**Comment by PhiSpel** [comment]
Do you have an example MATLAB-coded solution?

**Comment by joergbrech** [comment]
I sent you some code per mail 📫

**Comment by PhiSpel** [comment]
- [ ] add graphical output
- [ ] code should be parameter-independent
- [ ] suggest parameters
