### ISSUE TITLE
Add Matlab examples from the lecture slides

### ISSUE THREAD

**Issue by joergbrech** [joergbrech/Modellbildung-und-Simulation#92]
Though we agreed that this webpage is no place for theoretical background, it would still make sense to present the Matlab/programming examples from the lecture slides.

To Do:
 - [x] Go over the lecture slides of ModSim1 and ModSim2 and compile a list of programming examples from the lectures
 - [ ] Add the examples to this book. They need not be reformulated as exercises.

**Comment by PhiSpel** [comment]
see the closed PR #253
